# Generated by Django 4.1.7 on 2023-03-11 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('pID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=0)),
                ('num_ratings', models.PositiveIntegerField(default=0)),
                ('num_guests', models.PositiveIntegerField()),
                ('num_beds', models.PositiveIntegerField()),
                ('num_baths', models.PositiveIntegerField()),
                ('wifi', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('air_con', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('barbecue', models.BooleanField(default=False)),
                ('free_parking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('default', models.BooleanField(default=False)),
                ('image_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
