# Generated by Django 4.1.7 on 2023-03-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='pID',
            new_name='pid',
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
